# SPDX-FileCopyrightText: 2025 Forkbomb BV
#
# SPDX-License-Identifier: AGPL-3.0-or-later

min_version = '2025.1.8'

[tools]
go = "1.26.6"
bun = "1.3.12"
node = "24.13.0"
"aqua:dyne/slangroom-exec" = "latest"
pre-commit = "latest"
"github:forkbombeu/stepci-captured-runner" = { version = "latest", bin = "stepci-captured-runner" }
"github:forkbombeu/et-tu-cesr" = "latest"

[tools."github:temporalio/cli"]
version = "1.8.1"

