services:
  didimo:
    restart: unless-stopped
  postgresql:
    environment:
      POSTGRES_PASSWORD: d
      POSTGRES_USER: d
    image: postgres:13
  temporal:
    depends_on:
      - postgresql
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=d
      - POSTGRES_PWD=d
      - POSTGRES_SEEDS=postgresql
      - PROMETHEUS_ENDPOINT=0.0.0.0:8000
    image: temporalio/auto-setup:1.21.1
  temporal-admin-tools:
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.21.1
    stdin_open: true
    tty: true
  temporal-ui:
    depends_on:
      - temporal
    environment:
      - TEMPORAL_OPENAPI_ENABLED=true
      - TEMPORAL_UI_ENABLED=true
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_UI_PUBLIC_PATH=/workflows
      # - TEMPORAL_CODEC_ENDPOINT=http://localhost:8081
    image: temporalio/ui:2.32.0
    ports:
      - 8080:8080
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./deployment/prometheus/config.yml
        target: /etc/prometheus/prometheus.yml
  grafana:
    build: './deployment/grafana'
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_ROOT_URL=http://localhost:8085/monitoring
      - GF_SECURITY_ALLOWED_CORS_ORIGINS=http://localhost:8090
      - GF_SECURITY_CSRF_TRUSTED_ORIGINS=http://localhost:8090
      - GF_SECURITY_COOKIE_SAMESITE=disabled
      - GF_SECURITY_CONTENT_SECURITY_POLICY=false
      - GF_SERVER_HTTP_PORT=8085
      - GF_SECURITY_ACTIONS_ALLOW_POST_URL=/*
    ports:
      - 8085:8085
    volumes:
      - type: bind
        source: ./deployment/grafana/provisioning/datasources
        target: /etc/grafana/provisioning/datasources
  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - ./.certs:/certs
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: true
      MP_SMTP_AUTH_ALLOW_INSECURE: true
      MP_SMTP_TLS_CERT: /certs/mailpit+3.pem
      MP_SMTP_TLS_KEY: /certs/mailpit+3-key.pem
  thirdparty:
    build: deployment/thirdparty-simulator
    command: thirdparty-simulator api
    restart: unless-stopped
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
  # api:
  #   restart: unless-stopped
  #   environment:
  #     - TEMPORAL_GRPC_ENDPOINT=temporal:7233
  #     - DATACONVERTER_ENCRYPTION_KEY_ID=secret
  # ui:
  #   restart: unless-stopped
  #   environment:
  #     - TEMPORAL_GRPC_ENDPOINT=temporal:7233
  # worker:
  #   restart: unless-stopped
  #   environment:
  #     - TEMPORAL_GRPC_ENDPOINT=temporal:7233
  #     - DATACONVERTER_ENCRYPTION_KEY_ID=secret
  # tools:
  #   environment:
  #     - TEMPORAL_ADDRESS=temporal:7233
  #     - TEMPORAL_CLI_ADDRESS=temporal:7233
  #     - TEMPORAL_CODEC_ENDPOINT=http://dataconverter:8081/
  #     - TEMPORAL_CLI_CODEC_ENDPOINT=http://dataconverter:8081/
  # dataconverter:
  #   build:
  #     context: .
  #     target: app
  #   command: dataconverter-server --ui http://localhost:8080 --port 8081
  #   restart: unless-stopped
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - DATACONVERTER_ENCRYPTION_KEY_ID=secret
