# SPDX-FileCopyrightText: 2025 Forkbomb BV
#
# SPDX-License-Identifier: AGPL-3.0-or-later

services:
  credimi:
    restart: unless-stopped
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./deployment/prometheus/config.yml
        target: /etc/prometheus/prometheus.yml
  grafana:
    build: './deployment/grafana'
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_ROOT_URL=http://localhost:8085/monitoring
      - GF_SECURITY_ALLOWED_CORS_ORIGINS=http://localhost:8090
      - GF_SECURITY_CSRF_TRUSTED_ORIGINS=http://localhost:8090
      - GF_SECURITY_COOKIE_SAMESITE=disabled
      - GF_SECURITY_CONTENT_SECURITY_POLICY=false
      - GF_SERVER_HTTP_PORT=8085
      - GF_SECURITY_ACTIONS_ALLOW_POST_URL=/*
    ports:
      - 8085:8085
    volumes:
      - type: bind
        source: ./deployment/grafana/provisioning/datasources
        target: /etc/grafana/provisioning/datasources
  thirdparty:
    build: deployment/thirdparty-simulator
    command: thirdparty-simulator api
    restart: unless-stopped
    environment:
      - TEMPORAL_GRPC_ENDPOINT=credimi:7233
