services:
  didimo:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile.demo
      args: 
        - PUBLIC_POCKETBASE_URL=${COOLIFY_URL:-https://demo.didimo.forkbomb.eu/}
    environment:
      - ADDRESS_TEMPORAL=https://temporalui-demo.apps.forkbomb.eu
      - ADDRESS_GRAFANA=http://grafana:8085
      - ADDRESS_UI=http://localhost:5100
      - TEMPORAL_ADDRESS=temporal-demo.apps.forkbomb.eu:7233
      - APP_PATH=${COOLIFY_URL:-http://localhost:8090}
      - PUBLIC_POCKETBASE_URL=${COOLIFY_URL:-http://localhost:8090}
      - PORT=5100
      - SCHEMAS_PATH=schemas
      - DATA_DB_PATH=/pb_data/data.db
      - SMTP_HOST=smtp.apps.forkbomb.eu
      - SMTP_PORT=1025
      - MAIL_SENDER=didimo@forkbomb.eu
      - PB_ADMIN_USER=admin@example.org
      - PB_ADMIN_PASS=adminadmin
      - PB_TYPEGEN_EMAIL=admin@example.org
      - PB_TYPEGEN_PASSWORD=adminadmin
      - MAINTENANCE=false
    ports:
      - 8090:8090
    volumes:
      - ./pb_data:/pb_data
