services:
  credimi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PUBLIC_POCKETBASE_URL=https://demo.credimi.io
    environment:
      - SERVICE_FQDN_CREDIMI
      - SERVICE_FQDN_CREDIMI_8090
      - ADDRESS_TEMPORAL=http://localhost:8280
      - ADDRESS_GRAFANA=http://grafana:8085
      - ADDRESS_UI=http://localhost:5100
      - APP_PATH=${COOLIFY_URL:-http://localhost:8090}
      - DATA_DB_PATH=/usr/local/bin/pb_data/data.db
      - MAIL_SENDER=didimo@forkbomb.eu
      - RUN_STEPCI_PATH=pkg/OpenID4VP/stepci/runStepCI.js
      - SCHEMAS_PATH=schemas
      - SMTP_HOST=smtp.apps.forkbomb.eu
      - SMTP_PORT=1025
      - TEMPORAL_ADDRESS=localhost:7233
      - PORT=5100
    ports:
      - 8090:8090
      - 7233:7233
    volumes:
      - ./pb_data/:/usr/local/bin/pb_data
