services:
  didimo:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile.demo
    environment:
      - ADDRESS_TEMPORAL=http://temporal-ui:8832
      - ADDRESS_GRAFANA=http://grafana:8085
      - ADDRESS_UI=http://localhost:5100
      - PUBLIC_POCKETBASE_URL={$SERVICE_URL_DIDIMO_8090}
      - PORT=5100
      - MP_MAX_MESSAGES=5000
      - MP_SMTP_AUTH_ACCEPT_ANY=true
      - MP_SMTP_AUTH_ALLOW_INSECURE=true
      - MP_SMTP_TLS_CERT=/app/.certs/mailpit+3.pem
      - MP_SMTP_TLS_KEY=/app/.certs/mailpit+3-key.pem
      - PB_ADMIN_USER=admin@example.org
      - PB_ADMIN_PASS=adminadmin
      - PB_TYPEGEN_EMAIL=admin@example.org
      - PB_TYPEGEN_PASSWORD=adminadmin
      - TEST_USER_A_MAIL=userA@example.org
      - TEST_USER_A_PASS=userAuserA
      - TEST_USER_B_MAIL=userB@example.org
      - TEST_USER_B_PASS=userBuserB
      - MAINTENANCE=false
    ports:
      - 8090:8090
      - 8025:8025
    volumes:
      - ./pb_data/:/pb_data
