services:
  didimo:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile.demo
    environment:
      - ADDRESS_TEMPORAL=http://localhost:8832
      - ADDRESS_GRAFANA=http://grafana:8085
      - ADDRESS_UI=http://localhost:5100
      - PUBLIC_POCKETBASE_URL=$SERVICE_FQDN_DIDIMO
      - PORT=5100
      - PB_ADMIN_USER=admin@example.org
      - PB_ADMIN_PASS=adminadmin
      - PB_TYPEGEN_EMAIL=admin@example.org
      - PB_TYPEGEN_PASSWORD=adminadmin
      - TEST_USER_A_MAIL=userA@example.org
      - TEST_USER_A_PASS=userAuserA
      - TEST_USER_B_MAIL=userB@example.org
      - TEST_USER_B_PASS=userBuserB
      - MAINTENANCE=false
    ports:
      - 8090:8090
      - 7233:7233
    volumes:
      - ./pb_data/:/pb_data
