version: '3.8'

services:
  builder:
    image: alpine:latest
    working_dir: /app
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: Dockerfile.build
    command: make build

  # app:
  #   depends_on:
  #     - builder
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8090:8090"
  #     - "80:80"
  #   environment:
  #     DOMAIN: localhost

