# SPDX-FileCopyrightText: 2024 Puria Nafisi Azizi 
# SPDX-FileCopyrightText: 2024 The Forkbomb Company
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1
SPDX-PackageName = "DIDimo"
SPDX-PackageSupplier = "Puria Nafisi Azizi <puria@dyne.org>"
SPDX-PackageDownloadLocation = "https://github.com/ForkbombEu/didimo"

[[annotations]]
path = ["webapp/.vscode/extensions.json", "webapp/src/app.postcss", "webapp/project.inlang/project_id", "webapp/.env.example", "webapp/.npmrc"]
precedence = "override"
SPDX-FileCopyrightText = "2024 The Forkbomb Company"
SPDX-License-Identifier = "AGPL-3.0-or-later"
